/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KdsRouteImport } from './routes/_kds'
import { Route as KdsIndexRouteImport } from './routes/_kds/index'
import { Route as KdsReglagesRouteImport } from './routes/_kds/reglages'
import { Route as KdsPretesRouteImport } from './routes/_kds/pretes'
import { Route as KdsPizzaioloRouteImport } from './routes/_kds/pizzaiolo'
import { Route as KdsPaninoRouteImport } from './routes/_kds/panino'
import { Route as KdsFourRouteImport } from './routes/_kds/four'
import { Route as KdsCaisseRouteImport } from './routes/_kds/caisse'
import { Route as KdsAssistantRouteImport } from './routes/_kds/assistant'

const KdsRoute = KdsRouteImport.update({
  id: '/_kds',
  getParentRoute: () => rootRouteImport,
} as any)
const KdsIndexRoute = KdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KdsRoute,
} as any)
const KdsReglagesRoute = KdsReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => KdsRoute,
} as any)
const KdsPretesRoute = KdsPretesRouteImport.update({
  id: '/pretes',
  path: '/pretes',
  getParentRoute: () => KdsRoute,
} as any)
const KdsPizzaioloRoute = KdsPizzaioloRouteImport.update({
  id: '/pizzaiolo',
  path: '/pizzaiolo',
  getParentRoute: () => KdsRoute,
} as any)
const KdsPaninoRoute = KdsPaninoRouteImport.update({
  id: '/panino',
  path: '/panino',
  getParentRoute: () => KdsRoute,
} as any)
const KdsFourRoute = KdsFourRouteImport.update({
  id: '/four',
  path: '/four',
  getParentRoute: () => KdsRoute,
} as any)
const KdsCaisseRoute = KdsCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => KdsRoute,
} as any)
const KdsAssistantRoute = KdsAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => KdsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof KdsIndexRoute
  '/assistant': typeof KdsAssistantRoute
  '/caisse': typeof KdsCaisseRoute
  '/four': typeof KdsFourRoute
  '/panino': typeof KdsPaninoRoute
  '/pizzaiolo': typeof KdsPizzaioloRoute
  '/pretes': typeof KdsPretesRoute
  '/reglages': typeof KdsReglagesRoute
}
export interface FileRoutesByTo {
  '/assistant': typeof KdsAssistantRoute
  '/caisse': typeof KdsCaisseRoute
  '/four': typeof KdsFourRoute
  '/panino': typeof KdsPaninoRoute
  '/pizzaiolo': typeof KdsPizzaioloRoute
  '/pretes': typeof KdsPretesRoute
  '/reglages': typeof KdsReglagesRoute
  '/': typeof KdsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_kds': typeof KdsRouteWithChildren
  '/_kds/assistant': typeof KdsAssistantRoute
  '/_kds/caisse': typeof KdsCaisseRoute
  '/_kds/four': typeof KdsFourRoute
  '/_kds/panino': typeof KdsPaninoRoute
  '/_kds/pizzaiolo': typeof KdsPizzaioloRoute
  '/_kds/pretes': typeof KdsPretesRoute
  '/_kds/reglages': typeof KdsReglagesRoute
  '/_kds/': typeof KdsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/caisse'
    | '/four'
    | '/panino'
    | '/pizzaiolo'
    | '/pretes'
    | '/reglages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assistant'
    | '/caisse'
    | '/four'
    | '/panino'
    | '/pizzaiolo'
    | '/pretes'
    | '/reglages'
    | '/'
  id:
    | '__root__'
    | '/_kds'
    | '/_kds/assistant'
    | '/_kds/caisse'
    | '/_kds/four'
    | '/_kds/panino'
    | '/_kds/pizzaiolo'
    | '/_kds/pretes'
    | '/_kds/reglages'
    | '/_kds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  KdsRoute: typeof KdsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_kds': {
      id: '/_kds'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof KdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kds/': {
      id: '/_kds/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof KdsIndexRouteImport
      parentRoute: typeof KdsRoute
    }
    '/_kds/reglages': {
      id: '/_kds/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof KdsReglagesRouteImport
      parentRoute: typeof KdsRoute
    }
    '/_kds/pretes': {
      id: '/_kds/pretes'
      path: '/pretes'
      fullPath: '/pretes'
      preLoaderRoute: typeof KdsPretesRouteImport
      parentRoute: typeof KdsRoute
    }
    '/_kds/pizzaiolo': {
      id: '/_kds/pizzaiolo'
      path: '/pizzaiolo'
      fullPath: '/pizzaiolo'
      preLoaderRoute: typeof KdsPizzaioloRouteImport
      parentRoute: typeof KdsRoute
    }
    '/_kds/panino': {
      id: '/_kds/panino'
      path: '/panino'
      fullPath: '/panino'
      preLoaderRoute: typeof KdsPaninoRouteImport
      parentRoute: typeof KdsRoute
    }
    '/_kds/four': {
      id: '/_kds/four'
      path: '/four'
      fullPath: '/four'
      preLoaderRoute: typeof KdsFourRouteImport
      parentRoute: typeof KdsRoute
    }
    '/_kds/caisse': {
      id: '/_kds/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof KdsCaisseRouteImport
      parentRoute: typeof KdsRoute
    }
    '/_kds/assistant': {
      id: '/_kds/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof KdsAssistantRouteImport
      parentRoute: typeof KdsRoute
    }
  }
}

interface KdsRouteChildren {
  KdsAssistantRoute: typeof KdsAssistantRoute
  KdsCaisseRoute: typeof KdsCaisseRoute
  KdsFourRoute: typeof KdsFourRoute
  KdsPaninoRoute: typeof KdsPaninoRoute
  KdsPizzaioloRoute: typeof KdsPizzaioloRoute
  KdsPretesRoute: typeof KdsPretesRoute
  KdsReglagesRoute: typeof KdsReglagesRoute
  KdsIndexRoute: typeof KdsIndexRoute
}

const KdsRouteChildren: KdsRouteChildren = {
  KdsAssistantRoute: KdsAssistantRoute,
  KdsCaisseRoute: KdsCaisseRoute,
  KdsFourRoute: KdsFourRoute,
  KdsPaninoRoute: KdsPaninoRoute,
  KdsPizzaioloRoute: KdsPizzaioloRoute,
  KdsPretesRoute: KdsPretesRoute,
  KdsReglagesRoute: KdsReglagesRoute,
  KdsIndexRoute: KdsIndexRoute,
}

const KdsRouteWithChildren = KdsRoute._addFileChildren(KdsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  KdsRoute: KdsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
